export const ACCOUNT_CREATE_REQUEST = 'ACCOUNT_CREATE_REQUEST'
export const ACCOUNT_CREATE_SUCCESS = 'ACCOUNT_CREATE_SUCCESS'
export const ACCOUNT_CREATE_FAIL = 'ACCOUNT_CREATE_FAIL'
export const ACCOUNT_CREATE_RESET = 'ACCOUNT_CREATE_RESET'

export const ACCOUNT_BALANCE_REQUEST = 'ACCOUNT_BALANCE_REQUEST'
export const ACCOUNT_BALANCE_SUCCESS = 'ACCOUNT_BALANCE_SUCCESS'
export const ACCOUNT_BALANCE_FAIL = 'ACCOUNT_BALANCE_FAIL'
export const ACCOUNT_BALANCE_RESET = 'ACCOUNT_BALANCE_RESET'
