export const DEPOSIT_AMOUNT_REQUEST = 'DEPOSIT_AMOUNT_REQUEST'
export const DEPOSIT_AMOUNT_SUCCESS = 'DEPOSIT_AMOUNT_SUCCESS'
export const DEPOSIT_AMOUNT_FAIL = 'DEPOSIT_FAIL'
export const DEPOSIT_AMOUNT_RESET = 'DEPOSIT_RESET'

export const WITHDRAW_AMOUNT_REQUEST = 'WITHDRAW_AMOUNT_REQUEST'
export const WITHDRAW_AMOUNT_SUCCESS = 'WITHDRAW_AMOUNT_SUCCESS'
export const WITHDRAW_AMOUNT_FAIL = 'WITHDRAW_FAIL'
export const WITHDRAW_AMOUNT_RESET = 'WITHDRAW_RESET'

export const TRANSFER_AMOUNT_REQUEST = 'TRANSFER_AMOUNT_REQUEST'
export const TRANSFER_AMOUNT_SUCCESS = 'TRANSFER_AMOUNT_SUCCESS'
export const TRANSFER_AMOUNT_FAIL = 'TRANSFER_FAIL'
export const TRANSFER_AMOUNT_RESET = 'TRANSFER_RESET'
